# Site settings
title: Sam B. Fries
email: samuelbfries@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Beer and Tech. What could go wrong?
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.sambfries.me" # the base hostname & protocol for your site
github_username:  chaosphere2112

# Build settings
markdown: kramdown
